services:
  multi-agent-system:
    build: .
    container_name: multi_format_ai_system
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "6379:6379"
    restart: unless-stopped
